print(1 + 2)
print(1 - 2)
print(2 * 2)
print(3 % 2)
print(4 / 2)
print(2 ** 3)
print(3 // 2)

print('zain')
print('UK')
print('I am enjoying 30 days of python')

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type('zain'))
print(type("UK"))

print(type(True))
print(type(('Xbox', 499.99)))
print(type({1,2,3}))
print(type({"harry" : "styles"}))

print("The Euclidian distance between (2, 3) and (10, 8) is", ((2 - 10) ** 2 + (3 - 8) ** 2) ** 0.5)
